
    #ifndef IAGORAMEDIAPLAYER_C_H_
    #define IAGORAMEDIAPLAYER_C_H_
    
    #include <stdint.h>
    #include <stddef.h>
    
    
    
    #include "AgoraBase_C.h"
#include "AgoraMediaBase_C.h"
#include "AgoraMediaPlayerTypes_C.h"

typedef void* agora_rtc__IMediaPlayer__Handle;

int agora_rtc__IMediaPlayer__initialize(agora_rtc__IMediaPlayer__Handle handle,base__IAgoraService__Handle agora_service);
int agora_rtc__IMediaPlayer__getMediaPlayerId(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__open(agora_rtc__IMediaPlayer__Handle handle,const char* url,int64_t startPos);
int agora_rtc__IMediaPlayer__openWithCustomSource(agora_rtc__IMediaPlayer__Handle handle,int64_t startPos,agora_media_base__IMediaPlayerCustomDataProvider__Handle* provider);
int agora_rtc__IMediaPlayer__openWithMediaSource(agora_rtc__IMediaPlayer__Handle handle,const agora_media_base__MediaSource__C& source);
int agora_rtc__IMediaPlayer__play(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__pause(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__stop(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__resume(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__seek(agora_rtc__IMediaPlayer__Handle handle,int64_t newPos);
int agora_rtc__IMediaPlayer__setAudioPitch(agora_rtc__IMediaPlayer__Handle handle,int pitch);
int agora_rtc__IMediaPlayer__getDuration(agora_rtc__IMediaPlayer__Handle handle,int64_t& duration);
int agora_rtc__IMediaPlayer__getPlayPosition(agora_rtc__IMediaPlayer__Handle handle,int64_t& pos);
int agora_rtc__IMediaPlayer__getStreamCount(agora_rtc__IMediaPlayer__Handle handle,int64_t& count);
int agora_rtc__IMediaPlayer__getStreamInfo(agora_rtc__IMediaPlayer__Handle handle,int64_t index,agora_media_base__PlayerStreamInfo__C* info);
int agora_rtc__IMediaPlayer__setLoopCount(agora_rtc__IMediaPlayer__Handle handle,int loopCount);
int agora_rtc__IMediaPlayer__setPlaybackSpeed(agora_rtc__IMediaPlayer__Handle handle,int speed);
int agora_rtc__IMediaPlayer__selectAudioTrack(agora_rtc__IMediaPlayer__Handle handle,int index);
int agora_rtc__IMediaPlayer__setPlayerOption(agora_rtc__IMediaPlayer__Handle handle,const char* key,int value);
int agora_rtc__IMediaPlayer__setPlayerOption(agora_rtc__IMediaPlayer__Handle handle,const char* key,const char* value);
int agora_rtc__IMediaPlayer__takeScreenshot(agora_rtc__IMediaPlayer__Handle handle,const char* filename);
int agora_rtc__IMediaPlayer__selectInternalSubtitle(agora_rtc__IMediaPlayer__Handle handle,int index);
int agora_rtc__IMediaPlayer__setExternalSubtitle(agora_rtc__IMediaPlayer__Handle handle,const char* url);
agora_media_base__MEDIA_PLAYER_STATE__C agora_rtc__IMediaPlayer__getState(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__mute(agora_rtc__IMediaPlayer__Handle handle,bool muted);
int agora_rtc__IMediaPlayer__getMute(agora_rtc__IMediaPlayer__Handle handle,bool& muted);
int agora_rtc__IMediaPlayer__adjustPlayoutVolume(agora_rtc__IMediaPlayer__Handle handle,int volume);
int agora_rtc__IMediaPlayer__getPlayoutVolume(agora_rtc__IMediaPlayer__Handle handle,int& volume);
int agora_rtc__IMediaPlayer__adjustPublishSignalVolume(agora_rtc__IMediaPlayer__Handle handle,int volume);
int agora_rtc__IMediaPlayer__getPublishSignalVolume(agora_rtc__IMediaPlayer__Handle handle,int& volume);
int agora_rtc__IMediaPlayer__setView(agora_rtc__IMediaPlayer__Handle handle,agora_media_base__view_t__C view);
int agora_rtc__IMediaPlayer__setRenderMode(agora_rtc__IMediaPlayer__Handle handle,agora_media_base__RENDER_MODE_TYPE__C renderMode);
int agora_rtc__IMediaPlayer__registerPlayerSourceObserver(agora_rtc__IMediaPlayer__Handle handle,agora_rtc__IMediaPlayerSourceObserver__Handle* observer);
int agora_rtc__IMediaPlayer__unregisterPlayerSourceObserver(agora_rtc__IMediaPlayer__Handle handle,agora_rtc__IMediaPlayerSourceObserver__Handle* observer);
int agora_rtc__IMediaPlayer__registerAudioFrameObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media__IAudioPcmFrameSink__Handle* observer);
int agora_rtc__IMediaPlayer__registerAudioFrameObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media__IAudioPcmFrameSink__Handle* observer,agora_rtc__RAW_AUDIO_FRAME_OP_MODE_TYPE__C mode);
int agora_rtc__IMediaPlayer__unregisterAudioFrameObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media__IAudioPcmFrameSink__Handle* observer);
int agora_rtc__IMediaPlayer__registerVideoFrameObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media_base__IVideoFrameObserver__Handle* observer);
int agora_rtc__IMediaPlayer__unregisterVideoFrameObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media_base__IVideoFrameObserver__Handle* observer);
int agora_rtc__IMediaPlayer__registerMediaPlayerAudioSpectrumObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media__IAudioSpectrumObserver__Handle* observer,int intervalInMS);
int agora_rtc__IMediaPlayer__unregisterMediaPlayerAudioSpectrumObserver(agora_rtc__IMediaPlayer__Handle handle,agora_media__IAudioSpectrumObserver__Handle* observer);
int agora_rtc__IMediaPlayer__setAudioDualMonoMode(agora_rtc__IMediaPlayer__Handle handle,agora_media_base__AUDIO_DUAL_MONO_MODE__C mode);
const char* agora_rtc__IMediaPlayer__getPlayerSdkVersion(agora_rtc__IMediaPlayer__Handle handle);
const char* agora_rtc__IMediaPlayer__getPlaySrc(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__openWithAgoraCDNSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src,int64_t startPos);
int agora_rtc__IMediaPlayer__getAgoraCDNLineCount(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__switchAgoraCDNLineByIndex(agora_rtc__IMediaPlayer__Handle handle,int index);
int agora_rtc__IMediaPlayer__getCurrentAgoraCDNIndex(agora_rtc__IMediaPlayer__Handle handle);
int agora_rtc__IMediaPlayer__enableAutoSwitchAgoraCDN(agora_rtc__IMediaPlayer__Handle handle,bool enable);
int agora_rtc__IMediaPlayer__renewAgoraCDNSrcToken(agora_rtc__IMediaPlayer__Handle handle,const char* token,int64_t ts);
int agora_rtc__IMediaPlayer__switchAgoraCDNSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src,bool syncPts);
int agora_rtc__IMediaPlayer__switchSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src,bool syncPts);
int agora_rtc__IMediaPlayer__preloadSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src,int64_t startPos);
int agora_rtc__IMediaPlayer__playPreloadedSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src);
int agora_rtc__IMediaPlayer__unloadSrc(agora_rtc__IMediaPlayer__Handle handle,const char* src);
int agora_rtc__IMediaPlayer__setSpatialAudioParams(agora_rtc__IMediaPlayer__Handle handle,const agora__SpatialAudioParams__C& params);
int agora_rtc__IMediaPlayer__setSoundPositionParams(agora_rtc__IMediaPlayer__Handle handle,float pan,float gain);
typedef void* agora_rtc__IMediaPlayerCacheManager__Handle;

int agora_rtc__IMediaPlayerCacheManager__removeAllCaches(agora_rtc__IMediaPlayerCacheManager__Handle handle);
int agora_rtc__IMediaPlayerCacheManager__removeOldCache(agora_rtc__IMediaPlayerCacheManager__Handle handle);
int agora_rtc__IMediaPlayerCacheManager__removeCacheByUri(agora_rtc__IMediaPlayerCacheManager__Handle handle,const char* uri);
int agora_rtc__IMediaPlayerCacheManager__setCacheDir(agora_rtc__IMediaPlayerCacheManager__Handle handle,const char* path);
int agora_rtc__IMediaPlayerCacheManager__setMaxCacheFileCount(agora_rtc__IMediaPlayerCacheManager__Handle handle,int count);
int agora_rtc__IMediaPlayerCacheManager__setMaxCacheFileSize(agora_rtc__IMediaPlayerCacheManager__Handle handle,int64_t cacheSize);
int agora_rtc__IMediaPlayerCacheManager__enableAutoRemoveCache(agora_rtc__IMediaPlayerCacheManager__Handle handle,bool enable);
int agora_rtc__IMediaPlayerCacheManager__getCacheDir(agora_rtc__IMediaPlayerCacheManager__Handle handle,char* path,int length);
int agora_rtc__IMediaPlayerCacheManager__getMaxCacheFileCount(agora_rtc__IMediaPlayerCacheManager__Handle handle);
int64_t agora_rtc__IMediaPlayerCacheManager__getMaxCacheFileSize(agora_rtc__IMediaPlayerCacheManager__Handle handle);
int agora_rtc__IMediaPlayerCacheManager__getCacheFileCount(agora_rtc__IMediaPlayerCacheManager__Handle handle);
    
    #endif// IAGORAMEDIAPLAYER_C_H_
    