
    #ifndef IAGORAMEDIAPLAYERSOURCE_C_H_
    #define IAGORAMEDIAPLAYERSOURCE_C_H_
    
    #include <stdint.h>
    #include <stddef.h>
    
    
    
    #include "AgoraBase_C.h"
#include "AgoraMediaBase_C.h"
#include "AgoraMediaPlayerTypes_C.h"

typedef void* agora_rtc__IMediaPlayerSource__Handle;

int agora_rtc__IMediaPlayerSource__getSourceId(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__open(agora_rtc__IMediaPlayerSource__Handle handle,const char* url,int64_t startPos);
int agora_rtc__IMediaPlayerSource__openWithCustomSource(agora_rtc__IMediaPlayerSource__Handle handle,int64_t startPos,agora_media_base__IMediaPlayerCustomDataProvider__Handle* provider);
int agora_rtc__IMediaPlayerSource__openWithMediaSource(agora_rtc__IMediaPlayerSource__Handle handle,const agora_media_base__MediaSource__C& source);
int agora_rtc__IMediaPlayerSource__play(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__pause(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__stop(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__resume(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__seek(agora_rtc__IMediaPlayerSource__Handle handle,int64_t newPos);
int agora_rtc__IMediaPlayerSource__getDuration(agora_rtc__IMediaPlayerSource__Handle handle,int64_t& duration);
int agora_rtc__IMediaPlayerSource__getPlayPosition(agora_rtc__IMediaPlayerSource__Handle handle,int64_t& pos);
int agora_rtc__IMediaPlayerSource__getStreamCount(agora_rtc__IMediaPlayerSource__Handle handle,int64_t& count);
int agora_rtc__IMediaPlayerSource__getStreamInfo(agora_rtc__IMediaPlayerSource__Handle handle,int64_t index,agora_media_base__PlayerStreamInfo__C* info);
int agora_rtc__IMediaPlayerSource__setLoopCount(agora_rtc__IMediaPlayerSource__Handle handle,int64_t loopCount);
int agora_rtc__IMediaPlayerSource__setPlaybackSpeed(agora_rtc__IMediaPlayerSource__Handle handle,int speed);
int agora_rtc__IMediaPlayerSource__selectAudioTrack(agora_rtc__IMediaPlayerSource__Handle handle,int64_t index);
int agora_rtc__IMediaPlayerSource__setPlayerOption(agora_rtc__IMediaPlayerSource__Handle handle,const char* key,int64_t value);
int agora_rtc__IMediaPlayerSource__setPlayerOption(agora_rtc__IMediaPlayerSource__Handle handle,const char* key,const char* value);
int agora_rtc__IMediaPlayerSource__takeScreenshot(agora_rtc__IMediaPlayerSource__Handle handle,const char* filename);
int agora_rtc__IMediaPlayerSource__selectInternalSubtitle(agora_rtc__IMediaPlayerSource__Handle handle,int64_t index);
int agora_rtc__IMediaPlayerSource__setExternalSubtitle(agora_rtc__IMediaPlayerSource__Handle handle,const char* url);
agora_media_base__MEDIA_PLAYER_STATE__C agora_rtc__IMediaPlayerSource__getState(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__registerPlayerSourceObserver(agora_rtc__IMediaPlayerSource__Handle handle,agora_rtc__IMediaPlayerSourceObserver__Handle* observer);
int agora_rtc__IMediaPlayerSource__unregisterPlayerSourceObserver(agora_rtc__IMediaPlayerSource__Handle handle,agora_rtc__IMediaPlayerSourceObserver__Handle* observer);
int agora_rtc__IMediaPlayerSource__registerAudioFrameObserver(agora_rtc__IMediaPlayerSource__Handle handle,agora_media__IAudioPcmFrameSink__Handle* observer);
int agora_rtc__IMediaPlayerSource__unregisterAudioFrameObserver(agora_rtc__IMediaPlayerSource__Handle handle,agora_media__IAudioPcmFrameSink__Handle* observer);
int agora_rtc__IMediaPlayerSource__openWithAgoraCDNSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src,int64_t startPos);
int agora_rtc__IMediaPlayerSource__getAgoraCDNLineCount(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__switchAgoraCDNLineByIndex(agora_rtc__IMediaPlayerSource__Handle handle,int index);
int agora_rtc__IMediaPlayerSource__getCurrentAgoraCDNIndex(agora_rtc__IMediaPlayerSource__Handle handle);
int agora_rtc__IMediaPlayerSource__enableAutoSwitchAgoraCDN(agora_rtc__IMediaPlayerSource__Handle handle,bool enable);
int agora_rtc__IMediaPlayerSource__renewAgoraCDNSrcToken(agora_rtc__IMediaPlayerSource__Handle handle,const char* token,int64_t ts);
int agora_rtc__IMediaPlayerSource__switchAgoraCDNSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src,bool syncPts);
int agora_rtc__IMediaPlayerSource__switchSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src,bool syncPts);
int agora_rtc__IMediaPlayerSource__preloadSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src,int64_t startPos);
int agora_rtc__IMediaPlayerSource__unloadSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src);
int agora_rtc__IMediaPlayerSource__playPreloadedSrc(agora_rtc__IMediaPlayerSource__Handle handle,const char* src);
typedef void* agora_rtc__IMediaPlayerSourceObserver__Handle;

void agora_rtc__IMediaPlayerSourceObserver__onPlayerSourceStateChanged(agora_rtc__IMediaPlayerSourceObserver__Handle handle,agora_media_base__MEDIA_PLAYER_STATE__C state,agora_media_base__MEDIA_PLAYER_ERROR__C ec);
void agora_rtc__IMediaPlayerSourceObserver__onPositionChanged(agora_rtc__IMediaPlayerSourceObserver__Handle handle,int64_t position_ms);
void agora_rtc__IMediaPlayerSourceObserver__onPlayerEvent(agora_rtc__IMediaPlayerSourceObserver__Handle handle,agora_media_base__MEDIA_PLAYER_EVENT__C eventCode,int64_t elapsedTime,const char* message);
void agora_rtc__IMediaPlayerSourceObserver__onMetaData(agora_rtc__IMediaPlayerSourceObserver__Handle handle,const void* data,int length);
void agora_rtc__IMediaPlayerSourceObserver__onPlayBufferUpdated(agora_rtc__IMediaPlayerSourceObserver__Handle handle,int64_t playCachedBuffer);
void agora_rtc__IMediaPlayerSourceObserver__onPreloadEvent(agora_rtc__IMediaPlayerSourceObserver__Handle handle,const char* src,agora_media_base__PLAYER_PRELOAD_EVENT__C event);
void agora_rtc__IMediaPlayerSourceObserver__onCompleted(agora_rtc__IMediaPlayerSourceObserver__Handle handle);
void agora_rtc__IMediaPlayerSourceObserver__onAgoraCDNTokenWillExpire(agora_rtc__IMediaPlayerSourceObserver__Handle handle);
void agora_rtc__IMediaPlayerSourceObserver__onPlayerSrcInfoChanged(agora_rtc__IMediaPlayerSourceObserver__Handle handle,const agora_media_base__SrcInfo__C& from,const agora_media_base__SrcInfo__C& to);
void agora_rtc__IMediaPlayerSourceObserver__onPlayerInfoUpdated(agora_rtc__IMediaPlayerSourceObserver__Handle handle,const agora_media_base__PlayerUpdatedInfo__C& info);
void agora_rtc__IMediaPlayerSourceObserver__onAudioVolumeIndication(agora_rtc__IMediaPlayerSourceObserver__Handle handle,int volume);
    
    #endif// IAGORAMEDIAPLAYERSOURCE_C_H_
    